Run NTPD daily to sync time against network clock
aredn/aredn pull request #319
Opened 2022-03-25 00:52 UTC by aanon4

Here's a new NTPD proposal (requires the change in PR https://github.com/aredn/aredn/pull/317)

2022-03-25 00:52 UTC, aanon4 commented
https://github.com/aredn/aredn/issues/318

2022-03-25 02:46 UTC, ab7pa commented
The first script to use the periodic feature.  Looks good.

2022-03-25 02:54 UTC, dman776 requested changes

2022-03-25 02:54 UTC, dman776 commented on files/etc/mesh-release
> -3.1.1TUNNEL
Drop this file

2022-03-25 03:03 UTC, aanon4 commented on files/etc/mesh-release
> -3.1.1TUNNEL
Oops. Will fix it later this evening.

2022-03-25 04:49 UTC, aanon4 commented on files/etc/mesh-release
> -3.1.1TUNNEL
Fixed

2022-03-26 20:13 UTC, dman776 reviewed
I like it.   @ae6xe any feedback

2022-03-28 01:13 UTC, dman776 approved these changes

2022-03-28 01:13 UTC, merged