Support changing the VLAN tag on WAN
aredn/aredn pull request #329
Opened 2022-04-16 23:35 UTC by aanon4

Support changing the default VLAN tag for the WAN interface.
This comes up a bunch for people running complex networks (I had to buy a switch I use to specifically rewrite the VLAN tag of WANs) and providing this as an advance feature seems useful.
Also, added in a 'reboot' message for changing advance config options which need a reboot.

2022-04-17 02:09 UTC, r1de commented
:+1: :+1: :+1: :+1: :+1:

_years_ in the making.

2022-04-17 04:08 UTC, ae6xe requested changes
There are some devices where the wan port is on a switch chip, e.g. wbs510-v2 .   This means files that are initialized on firstboot are created with this information to update the switch settings.   See the files /etc/aredn_include/swconfig.   Also, in openwrt upgrade branch, I had added the wan port to be on 2 different ports (added vlan 1 to the dtdlink vlan 2 port on the hap ac lite).   This way a user could use 1 cat5 cable to have wan and dtdlink, instead of 2 cables on 2 ports.

2022-04-17 04:14 UTC, ae6xe commented
After applying patches, look at the files linux/ath79/base-files/etc/board.d/02_network, and target/linux/ar71xx/base-files/etc/board.d/02_network.   If you see this notation, a device that uses the swconfig for setting vlan 1 is used:

 ucidef_add_switch "switch0" \
                        "0@eth0" "2:lan" "3:lan" "4:lan" "1:wan" "5t:dtdlink"

the order in this file determines the vlan used.  lan is first so gets a '0',  then wan, so gets a '1', then "dtdlink", so gets a 2 auto assigned.  

To change this assignment on a live node, the detail in /etc/board.json needs updated, and first boot scripts create the swconfig files, which then is included in /etc/config/network on save settings.

2022-04-17 04:23 UTC, aanon4 commented
As a way to move this forwards we could not support this feature on devices which contain switches?

2022-04-17 04:27 UTC, aanon4 commented
The incoming multiple-wan port change should be fine with this change I think. I mean, it totally neutral if you don't use it, and my old NSM5 already has multiple wan ports and this change was fine with that.

2022-04-17 04:38 UTC, ae6xe commented
These are the affected devices

**ar71xx images:**
cpe210
cpe220-v2
cpe220-v3
cpe510
wbs210
wbs510
gl-ar750s
nanostation-m-xw 
**ath79 images:**
gl-ar750s

I'd put out for others to weigh in on excluding these.    Best to detect if there is a vlan 1 in the swconfig file or board.json to hide the option, in case my list has an error.   I wouldn't want to hold hostage the devices this commit will work on to have this feature for the above devices -- it is incremental value delivered.

2022-04-17 04:39 UTC, aanon4 commented
I went with simply not including the feature if there was *anything* in the swconfig file, which seemed like the safest option.

2022-04-17 04:48 UTC, ae6xe commented
There are several devices, e.g. the hap ac lite, where there is a switch for eth0 - lan and dtdlink.  But the wan is on eth1.   swconfig will be populated, but does not contain vlan1 and the code on this commit should work.

2022-04-17 04:56 UTC, ae6xe commented
check this code doesn't change the setting on the hap ac lite, GL-AR150, GL-AR300M16, and GL-AR750.  On these devices, the WAN port is "untagged", and the config settings should not change.

2022-04-17 05:07 UTC, aanon4 commented
I think we should let the hAP go for now also - start with what will definitely work and add to it later.
I have checked the GL-AR150 (my usual debugging box) and it correctly switches from untagged to tagged traffic as I'd expect when setting a tagged device for WAN.

2022-04-17 05:51 UTC, r1de commented
I can possibly try to test this on one of our easily accessible "other vlan" devices tomorrow, just have to see how the day goes. 🤞 
From talking with Tim though, I think it'll be just fine.

2022-04-17 06:09 UTC, aanon4 commented
More thoughts on hAP and switches: Once switches get involved there are lots and lots of configuration options available to the avid tinkerer. Even with the hAP there's no reason someone couldn't assign the WAN to a VLAN on the switch even though that's not what happens today.

So how about this approach. For "simple" (ie. no switch) devices we can use this change which gives easily changeable VLANs on many devices (where what is happening is obvious to the modest hacker). For people who really want to change things up, we do a follow-on which doesn't attempt to add UI for complex changes, but instead finds a way to persist these changes across upgrades (unlike today). Thoughts?

2022-04-17 06:45 UTC, ae6xe commented
Huge limitation with the vlan implementation.   A given port can not share untagged  with tagged.

2022-04-17 06:53 UTC, aanon4 commented
> Huge limitation with the vlan implementation. A given port can not share untagged with tagged.

I assume you mean a switch port, yes? If we continue to exclude devices with switch chips in this PR, that shouldn't matter (I think).

2022-04-17 07:08 UTC, ae6xe commented
Yes, Only relevant if there becomes more options for end users to do custom switch port configurations.

2022-04-17 18:08 UTC, aanon4 commented
Having slept on this a bit I think I'm going to tweak how the UI presents itself slightly. Rather than letting you specific the device to use (which is easy to implement) I'm going to switch to letting you specify the VLAN ID to use. This should make adapting this change for switch-enabled devices more sane.

2022-04-17 20:45 UTC, aanon4 commented
Okay - same supported devices as before (so still nothing with a switch) but now specify just the VLAN ID for the WAN. This will make propagating the changes to devices with switches easier to do.  The original PR let you not only change VLAN ID but also the device itself which was undesirable, even in an advance option.

2022-04-18 17:48 UTC, aanon4 commented
@r1de any chance you can give this a whirl before tomorrow evening?

2022-04-18 20:33 UTC, r1de commented
I will try, not getting home till about 6pm tho.

2022-04-19 19:34 UTC, r1de commented
Tested on one of our local customized devices and WAN interface VLAN ID switching works.
Went from VLAN 1 to VLAN 15. :+1: 
But, hold up, don't celebrate just yet... I re-flashed it, _with the same code_, just now, and it seems to have _not_ retained the VLAN ID change.
More on this once I can get back into that device. On our network if VLAN 15 goes away, the network breaks apart, and of course, I am on the wrong side.

2022-04-19 21:28 UTC, aanon4 commented
There are various places the code sanity checks _setup and I missed one in the upgrade path - fixed now.

2022-04-20 00:11 UTC, r1de commented
Re-tested with new commit and VLAN ID is now retained across upgrades.
Nice work!!  :+1: :tada:

2022-04-20 00:20 UTC, ae6xe commented
Is this ready to commit to the repo?   Which devices did this end up to being applicable to (or not applicable to)?

2022-04-20 00:22 UTC, aanon4 commented
Yes. We've finished testing it and it looks good.

It is limited to devices without a switch chip. I can build a complete list of supported/unsupported devices for the final release notes.

2022-04-20 00:24 UTC, ae6xe approved these changes
tested by Eric r1de.

2022-04-20 00:24 UTC, merged

2022-04-20 00:50 UTC, dman776 commented
I think we need to discuss.   Can we do this for all devices?

2022-04-20 00:52 UTC, dman776 commented
resolves #51

2022-04-20 00:59 UTC, aanon4 commented
This doesn't do it for all devices, but yes we can do this for all devices. Those currently unsupported all contain switches, which is trickier, and I don't have enough of them (yet) to test that work. Despite that I think its valuable to support what we can now.

Somewhat randomly this is the first thing I ever wanted to change on my AREDN nodes as VLAN-1 is a no-go on my home network. Ended up buying a switch cable of re-writing VLAN tags to deal with the issue. This is cheaper :-)

2022-04-20 01:00 UTC, dman776 commented
Need to update README.md to indicate that vlan 1 is the WAN port (by default, but, can be changed in Adv Config)

2022-04-20 01:05 UTC, dman776 commented
any changes needed to /usr/lib/lua/aredn/hardware.lua - get_iface_name()
updates also needed to /www/help.html (WAN Wifi Client section references vlan1)

2022-04-20 01:06 UTC, aanon4 commented
/usr/lib/lua/aredn/hardware.lua - get_iface_name() is good as it is.

2022-04-20 01:07 UTC, aanon4 commented
I'll annoy @ab7pa about the best way to update the help information and documenting the adv option.

2022-04-20 01:08 UTC, dman776 commented
we need that also, but, the readme.md and help.html are in this repo and should be clarified.

2022-04-20 01:19 UTC, dman776 commented
should we change that the vlan input is numeric, between 1 and 4094, and not 2 (dtd)??

2022-04-20 01:20 UTC, r1de commented
I should add that this tested on a _live_ network.
and +1 to what @dman776 just said ^^ block VLAN2.

2022-04-20 01:22 UTC, aanon4 commented
I decided that the very big scary red warning at the top of this page was sufficient. I don't think there's validation on any other setting here.

2022-04-20 01:28 UTC, aanon4 commented
@ae6xe Yes, but I don't have enough devices with switches, so once some I get them I'll work on the changes.