Ping tool (to complement the iperf3 tool)
aredn/aredn pull request #440
Opened 2022-07-19 23:21 UTC by aanon4

This is a simple ping tool to complement the existing iperf3 tool. It allows someone to initiate a ping test from any node to any other node. The test is limited to 10 seconds.

The goal is to enable improved network monitoring by allowing specific links in the network to be tested. Right now, although nodes can be tested, the path will always be from the initiator to the target, which is not necessarily what you want.

2022-07-19 23:34 UTC, ab7pa approved these changes
Works well on my test node.

<img width="738" alt="Screen Shot 2022-07-19 at 4 32 57 PM" src="https://user-images.githubusercontent.com/69524416/179865526-5b19e1a2-7d67-4c7d-a051-1d14023ebee4.png">

2022-07-20 00:18 UTC, dman776 commented
What do you think about adding a getPing function to aredn.utils and exposing in the api.   This is the same approach as the traceroute takes.   http://localnode.local.mesh:8080/cgi-bin/api?traceroute=TARGETNODENAME
it could be: http://192.168.0.47:8080/cgi-bin/api?ping=TARGETNODENAME

2022-07-20 00:19 UTC, dman776 requested changes
see comment about adding to api

2022-07-20 00:22 UTC, aanon4 commented
I had no idea that was even there!
Could do - was just using iperf as a basis for this, but could use traceroute instead - not fussed either way

2022-07-20 00:27 UTC, ab7pa commented
I'll wait to wrap up the documentation for this feature until we decide whether to accomplish it through cgi-bin/ping or cgi-bin/api -- either way it looks like a good addition.  I suppose that cgi-bin/iperf could eventually be converted to the api approach at some point.  Thanks, @aanon4 Tim!

2022-07-20 00:38 UTC, dman776 commented
May as well move them to api for future.   We can always have a "html" readable page in the interim that essentially calls the api and formats for html if you think it's necessary.   That is my strong preference.

2022-07-20 01:01 UTC, ab7pa commented
One issue with using cgi-bin/api is that the results are displayed in json rather than in plain text in the browser.  This PR still seems valuable (as well as cgi-bin/iperf) for displaying the results in simple text.

2022-07-20 01:17 UTC, dman776 commented
See previous comment

Thanks,
Darryl

> On Jul 19, 2022, at 8:01 PM, Steve AB7PA ***@***.***> wrote:
> 
> ﻿
> One issue with using cgi-bin/api is that the results are displayed in json rather than in plain text in the browser. This PR still seems valuable (as well as cgi-bin/iperf) for displaying the results in simple text.
> 
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because your review was requested.

2022-07-20 01:26 UTC, dman776 commented
also, is the ttl value needed?   It's always going to be the same 64, right?

2022-07-20 01:26 UTC, aanon4 commented
Bump.
TTL - I decided to include all the information I was given, because maybe it would be useful.

2022-07-20 01:27 UTC, merged